version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foo.local.test
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
      - plone

  plone:
    build:
      context: .
      args:
        DEVEL: 'yes'
    image: 'cloudplone/cms:dev'
    ports:
      - "8080:8080"
